### ISSUE TITLE
OpenGraph social preview for profiles

### ISSUE THREAD

**Issue by nadimkobeissi** [capsulesocial/capsule-vue#691]
Right now, when I share *any* profile, for example, https://blogchain.app/id/la_devochka — I get this:

<img width="571" alt="CleanShot 2022-03-24 at 4 02 41@2x" src="https://user-images.githubusercontent.com/9953/159946184-07266fd1-4342-40c0-a442-62c219e0dcc5.png">

We should have something similar to what we accomplished with shareable links: real OpenGraph metadata for profiles, including the profile picture, username, full name, and bio.

**Comment by ashutosh1206** [comment]
Fixed in https://github.com/capsulesocial/capsule-server/pull/280 and https://github.com/capsulesocial/capsule-vue/pull/1151
